name: Build EXE

on:
  push:
    branches: [ main ]  # or "v1" or any branch you want to trigger from
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or your python version

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile PDFdownloader.py

      - name: Upload EXE
        uses: actions/upload-artifact@v3.1.3
        with:
          name: PDFdownloader-exe
          path: dist/PDFdownloader.exe
