name: Build EXE with PyInstaller

on:
  push:
    branches: [ main ]  # or "v1" or any branch you want to trigger from
  workflow_dispatch:    # allows manual run from GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Change if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile WordMacro.py

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WordMacro-exe
        path: dist/WordMacro.exe
